### ISSUE TITLE
Problem at plot selection

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-cadastrapp#67] opened 2021-02-15 15:15 UTC
I installed the extension with the provided ZIP and had an error at plot selection : 

The WFS request to retrieve the clicked parcel is done on the 'cadastre.wms.layer.name' config parameter which correspond to the WMS layer to load at the plugin activation.

It should be done over 'parcelle.wms.layer.name' instead. 

The problem is the same for point, linear and polygon selection.

**Comment by jusabatier** [comment] 2021-02-15 15:16
Tested with the plot search function, it look to have the same problem

**Comment by jusabatier** [comment] 2021-02-15 15:38
Sorry as it is for WFS Request, I think the cadastrapp conf to use is more 'cadastre.wfs.layer.name'

For now I get the problem for each WFS request done to retrieve parcel (selection, search plot and owner, UF search, ...)

**Comment by landryb** [comment] 2021-02-16 15:11
can confirm the issue, wrong layer used. `cadastre.wfs.url` + `cadastre.wfs.layer.name` should be used for the plot selection, as documented in https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/resources/cadastrapp.properties#L97

as an example, in our production instance we use a mapproxy layer for `cadastre.wms.url` (so this service **doesnt** support WFS) and we point at geoserver for `parcelle.wms.url`, `cadastre.wfs.url` and `uf.wfs.url`.

**Comment by landryb** [comment] 2021-02-16 15:19
looking at the json returned by `/cadastrapp/services/getConfiguration` my understanding is that `cadastreWMSLayerName` is used instead of `cadastreWFSLayerName` for the plot selection. `cadastreWFSLayerName` isnt referenced anywhere in https://github.com/georchestra/mapstore2-cadastrapp/blob/master/js/extension/epics/setup.js#L72, only `cadastreWFSURL`.

**Comment by landryb** [comment] 2021-02-16 15:25
`ufWFSLayerName` and `ufWFSURL` values dont seem used anywhere in the code either, that's probably wrong.

**Comment by offtherailz** [comment] 2021-02-16 15:55
Yes, @landryb exactly. 
I see two issues:
1. About cadastreWFSLayerName, I think the issue can be fixed by setting the proper feature type name here: 
https://github.com/landryb/mapstore2-cadastrapp/blob/a943d7d4d6c11f255573972ef712a761f7aec76e/js/extension/epics/mapSelection.js#L51
2. Yes`ufWFSLayerName' and `ufWFSURL` are not actually used, parcelle feature is used instead.  Looking at the original code I see there is a replacement of features removing the original with the one coming from the other service, with the same "point" filter. Because of the new-tab open I didn't noticed this replacement, also because the features are identical, at least most of the times.

**Comment by landryb** [comment] 2021-02-16 16:12
my potential fix didnt work, so i'll let you properly fix the issue, we really need a fix to be able to properly test cadastrapp as this basic feature is used everywhere.

I dont know this redux code enough to dive in this nightmare :)

**Comment by landryb** [comment] 2021-02-16 16:32
Hah! victory. https://github.com/landryb/mapstore2-cadastrapp/actions/runs/572177132 correctly uses the right layer name for the WFS layer query.

**Comment by landryb** [comment] 2021-02-16 16:36
that wont completely solve this issue as `ufWFSLayerName` (which is **different** from parcelle feature) isnt used but #70 is a start.

**Comment by landryb** [comment] 2021-02-17 08:15
and i can confirm that the wrong geometry is shown on the 'show unite fonciere' window, it's the plot that seems to come from the previous request (ie no 'new' WMS/WFS query is done) that is shown. Apparently in the previous client, a WFS POST was done on the layer referenced by `ufWFSLayerName`

**Comment by offtherailz** [comment] 2021-02-18 11:48
@landryb  Most of the times the geometry is exactly the same. Can you give me an example feature in Rennes when the two geometries differ, so I can better figure out what the original implementation did?
Looking at the original code, the first query is done on parcelle layer, then the same query (with the same point intersection filter) is forwarded to the "uf" layer (`ufWFSLayerName`). This looks a little bit strange to me, because if the geometries are different, maybe also the clicked parcelle and the geometry shown may differ (and in the corner case, do not match the clicked point). Can you confirm this behavior? Maybe if I see the example I asked, I can clarify also this point. Thank you

**Comment by landryb** [comment] 2021-02-18 14:33
i dont work at rennes so i have no idea what's in their cadastre layers, but to me an uf geometry should be the merging of all neighbour parcelles belonging to the same owner - care to confirm @MaelREBOUX ?

**Comment by landryb** [comment] 2021-02-18 14:37
![image](https://user-images.githubusercontent.com/3421760/108372164-d3901880-71fe-11eb-9b41-ddfdbbd3563b.png)

that's an uf geometry from the `pci:geo_unite_fonciere_2020` layer from our geoserver in our mapfishapp, overlayed on top of the cadastre layer from mapproxy.

try it on http://cadastre.craig.fr, recenter on `Lon = 3.42928, Lat = 45.704`, click 'unite fonciere' then select one of the parcels.

**Comment by offtherailz** [comment] 2021-02-18 16:14
Ok, thank you very much.
I started developing this feature from the parcelle --> UF button. In this case the geometry of the parcelle is shown instead.
![Peek 18-02-2021 17-03](https://user-images.githubusercontent.com/1279510/108385396-e9580a80-720b-11eb-8460-d7660992696f.gif)
So I didn't noticed that in the case of the direct use of UF button, the feature was replaced by this, also because it is exactly the same most of the times. 
I think this is because is impossible to use the same query (intersection with the clicked point) from the parcelle table record, that could be a result of a normal search. 
Should I keep the same behavior also in the table use case, isn't it? (I don't see any way to query the wfs layer with the parcelle info) 

If you confirm I'll proceed with the fix.

**Comment by offtherailz** [comment] 2021-02-18 16:26
I don't know if I can create a better wfs query that fits both the case? The only attribute I see in common between them is the `comptecommunal` but I don't know if it is unique for every UF. Is it?

**Comment by landryb** [comment] 2021-02-19 07:33
i have to admit i have zero idea, i'll let the experts comment on the feature itself ... @jusabatier @MaelREBOUX ? iirc the geometry differs as soon as an owner has several neighbouring plots..

**Comment by MaelREBOUX** [comment] 2021-02-24 16:34
@pierrejego  we need help here because I don't know exactly how the code works in our curretn cadastrapp / mapfishapp version.

> Most of the times the geometry is exactly the same

Mostly yes but when not it is sooo very interesting for landing management. On rennes @offtherailz  you could go to the 350238000CK0278 parcel and click onto with the Unite Foncière tool.

with the current cadastrapp : the UF from the unite fonciere layer :

![image](https://user-images.githubusercontent.com/6370443/109032782-49482880-76c6-11eb-99b1-4783465695d2.png)


with mapstore : only the parcel

![image](https://user-images.githubusercontent.com/6370443/109032661-2cabf080-76c6-11eb-9ab7-a3a39f325b39.png)

**Comment by MaelREBOUX** [comment] 2021-02-25 09:24
As far as I remember, the code shoud does :

1.  click on the map
2. send request to GeoServer on `cadastre.wfs.layer.name` with parcel ID
3. get the geometry of the parcel as result
4. send another request to GeoServer on `uf.wfs.layer.name` with the parcel geometry (intersect ?)
5. get the WFS result of the Unité Foncière
6. show on the map in a "drawing layer"
7. do the rest....

**Comment by MaelREBOUX** [comment] 2021-02-25 09:32
well : I think that what I said before is done on backend side.

but all seems to start here : https://github.com/georchestra/cadastrapp/blob/cb8c6c4650891cae31e925facddaf78a0875196e/addons/cadastrapp/js/ficheUniteFonciere.js#L202
and here
https://github.com/georchestra/cadastrapp/blob/cb8c6c4650891cae31e925facddaf78a0875196e/addons/cadastrapp/js/ficheUniteFonciere.js#L66

**Comment by pierrejego** [comment] 2021-02-25 09:56
Hello, @MaelREBOUX  here is the code corresponding 

for information selection on UF from plot was made here 
https://github.com/georchestra/cadastrapp/blob/cb8c6c4650891cae31e925facddaf78a0875196e/addons/cadastrapp/js/selectFeature.js#L250

https://github.com/georchestra/cadastrapp/blob/cb8c6c4650891cae31e925facddaf78a0875196e/addons/cadastrapp/js/selectFeature.js#L263

A filter was developp to get the UF geometry linked to to the plot geometry

**Comment by landryb** [comment] 2021-02-26 08:28
As reminded by @catmorales, it also seems there are some layers/service parameters client-side (cf https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/config.json) which arent found in this version - i dont really remember what they were for though

**Comment by offtherailz** [comment] 2021-02-26 13:43
Thank you. I've seen the intersection query with the other layer uses the clicked point as geometry. 
If there is not a better way I can proceed this way.
The only issue doing it this way is that the same functionality accessed from the parcel grid, will not be able to show the UF.
T
he same behavior of the original cadastrapp, see [this comment](https://github.com/georchestra/mapstore2-cadastrapp/issues/67#issuecomment-781457401))

**Comment by offtherailz** [comment] 2021-03-02 12:14
Fixed to retrive and use UF geometry, when possible, as in the original application. Thank you for your comments. Please check.

**Comment by tdipisa** [comment] 2021-03-30 14:48
@landryb @jusabatier can we close this?

**Comment by landryb** [comment] 2021-03-30 14:53
i havent been able to test as i'm still puzzled by this notion of UF and what it means and what layer should be used, but @jusabatier and @MaelREBOUX should confirm you when it's okay to close.

afaict 75f1f9a75 starts using the right layer, but i'm not able to say it fixes all specific cases.

**Comment by jusabatier** [comment] 2021-03-31 09:29
Tested and validated for plots.

But I doesn't know an UF to test it.

@MaelREBOUX  ?

**Comment by landryb** [comment] 2021-04-09 09:25
@offtherailz here @stous tested this feature and it doesnt seem to work, we've deployed 1.0.0-rc7 (so includes 75f1f9a) in production on https://ids.craig.fr/mapstore/#/context/cadastre and looking for parcel 630177000AB0152 (church in isserteaux), asking for the UF window, there are two problems:

- it says that the UF there are 3 parcels, but it only lists 2 parcel IDs out of 3 (but shows 3 areas)
- the map only shows/highlights the church parcel, while we would expect the map to highlight 3 parcels

![image](https://user-images.githubusercontent.com/3421760/114159487-22684d80-9926-11eb-9af3-596f4e616a38.png)

on top of this, sometimes the aerial background is shown, sometimes not.

hope those STRs will help you reproduce.

**Comment by MaelREBOUX** [comment] 2021-05-05 13:09
Ok. Let's test (sory to be sooo late) with with the last available build : https://github.com/georchestra/mapstore2-cadastrapp/suites/2379569218/artifacts/50518522

in the UI :

![image](https://user-images.githubusercontent.com/6370443/117145632-a55cb680-adb3-11eb-9d3e-9d0c454f6786.png)


in the PDF

![image](https://user-images.githubusercontent.com/6370443/117145681-af7eb500-adb3-11eb-8225-bbae37898671.png)


We have the UF datas.

Good job ! I close.

**Comment by landryb** [comment] 2021-05-05 13:20
well as i shown above in my previous comment, it doesnt seem to work for us ? note that i'm 'manually' deploying cadastrapp addon in `/etc/georchestra/mapstore/dist/extensions/Cadastrapp/` (eg not via context creator) - dunno if this matters.

**Comment by tdipisa** [comment] 2021-05-05 14:30
@offtherailz can you check this?

**Comment by landryb** [comment] 2021-05-06 13:58
just retested to be sure with 1.0.0-rc9 deployed in our development environment (by removing `/etc/georchestra/mapstore/dist/extensions/Cadastrapp/*`, unzipping Cadastrapp.zip from https://github.com/georchestra/mapstore2-cadastrapp/actions/runs/816093947 in that folder), reloaded mapstore webapp, force-reloaded the context in the browser to make sure the new css/js was used (yes, it was fetched), and i can still reproduce the problem per https://github.com/georchestra/mapstore2-cadastrapp/issues/67#issuecomment-816550730

the window shows 3 areas, but only 2 plot IDs, and the map only shows the geometry for plot 630177000AB0152 (which is the only geometry fetched ... eg the geometry of the UF isnt fetched)

surprisingly if i try to print the document as pdf, the 3 plots IDs are displayed but the geometry is still wrong:

![image](https://user-images.githubusercontent.com/3421760/117309623-e2dc4500-ae82-11eb-918f-eda286835c44.png)


for reference, the relevant calls made to the API:
* a POST done to https://ids.craig.fr/wxs/pci/wfs?service=WFS&outputFormat=json with `<wfs:GetFeature service="WFS" version="1.1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="pci:geo_parcelle_2020" srsName="EPSG:4326"><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>geo_parcelle</ogc:PropertyName><ogc:Literal>630177000AB0152</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter></wfs:Query></wfs:GetFeature>`
* https://ids.craig.fr/cadastrapp/services/getInfoUniteFonciere?parcelle=630177000AB0152 (that one returns the reference of the UF, eg 5542542)
* https://ids.craig.fr/cadastrapp/services/getParcelle?unitefonciere=5542542 (that one lists the 3 plots)

at *no* point i saw a WFS request targetting `uFWFSLayerName` which is "pci:geo_unite_fonciere_2020" here, while from my understanding the geometry displayed should come from this layer... for reference, here's the request made by the older cadastrapp when using the 'click to select UF' tool, where we can see the target layer is correct:

url https://ids.craig.fr/wxs/pci/wfs, POST `<wfs:GetFeature service="wfs" version="1.0.0" outputFormat="application/json" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd"><wfs:Query typeName="pci:geo_unite_fonciere_2020"><Filter xmlns:gml="http://www.opengis.net/gml"><Contains><PropertyName>geom</PropertyName><gml:Point><gml:coordinates>376980.39188662,5724841.8467379</gml:coordinates></gml:Point></Contains></Filter></wfs:Query></wfs:GetFeature>` -> that returns the geometry for the complete UF including plots 150. 151 and 152.

**Comment by landryb** [comment] 2021-05-07 11:22
we finally found out with @maelreboux where the problem was .. if you use the `unite fonciere` tool in the 'main' toolbar (eg select tool, click on plot), it works fine, the UF geometry is shown - i guess that's the codepath 75f1f9a fixed.

*but* there's a second codepath that needs fixing: use the `point selection plot` tool, click on a plot, select it in the search result, click on the small `unite fonciere` button in the selection results toolbar (the one with 'export as csv') and the resulting window wont show the UF geometry. @MaelREBOUX can reproduce the issue with `1.0.0-rc9`.

@offtherailz now you should have everything :)

**Comment by MaelREBOUX** [comment] 2021-05-07 13:07
![image](https://user-images.githubusercontent.com/6370443/117454038-f8ff0980-af45-11eb-9575-e34ebe8c7ae4.png)

**Comment by offtherailz** [comment] 2021-05-07 16:24
Maybe a solution ( if a wfs query is not possible ) could be to indicate somewhere in the UI that using the tool from the grid will not retrive the UF geometry?

**Comment by landryb** [comment] 2021-05-10 06:23
ooh, now i get it ..

sadly, it doesnt seem the UF layer has the UFID field (it would have helped..), so i see three ways to get the UF geometry from the plot id:
- calling `cadastrapp/services/getInfoUniteFonciere?parcelle=PLOTID` returns you json with the UFID, calling `/cadastrapp/services/getParcelle?unitefonciere=UFID` gives you the plot ids of all the plots in the UF, and from that you should be able to do a WFS query on the plot layer with a filter using the list of plot ids, then assemble the returned geometries. a bit awkward
- you have the plot id, so you can get its geometry from a WFS query on the plot layer filtered on the plot id, take a random point within the plot (center? but one needs to make sure its within..), then do a second WFS query on the UF layer with that point

**Comment by landryb** [comment] 2021-05-10 11:42
tested this archive on my dev instance, works fine here ! ok to merge #120 and close this issue :) many thanks !

**Comment by offtherailz** [comment] 2021-05-10 13:29
Merged and published the rc. so closing this issue.

**Closed** 2021-05-10 13:28 UTC
Labels: CADASTRAPP, Contract #2, Priority: Medium, User feedback, investigation

**Comment by MaelREBOUX** [comment] 2021-05-10 13:49
I just redeployed with the latest build https://github.com/georchestra/mapstore2-cadastrapp/actions/runs/827941013 to test.

I confirm it is ok now.
